deployments:
  default:
    dockerimage: ubuntu:latest
    build_steps:
      - apt-get update && apt-get install -y libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev curl
      - RUN bash -c "curl -sL https://deb.nodesource.com/setup_18.x | bash -"
      - apt install -y nodejs
      - cd /code
      - npm install --legacy-peer-deps
    launch_steps:
      - npm run serve
    port_forwarding: 80:3000
    run_options: 
      - --env REACT_APP_TALAWA_URL="https://talawaapi.azurewebsites.net/graphql"
